### PR TITLE
Check for deprecated fastutil methods

### PR DESCRIPTION
**Pull request by jtraglia**
This check will identify calls to `entrySet` instead of type-specific `entrySet` calls like:

* https://fastutil.di.unimi.it/docs/it/unimi/dsi/fastutil/ints/Int2LongMap.html#int2LongEntrySet()
* https://fastutil.di.unimi.it/docs/it/unimi/dsi/fastutil/ints/Int2BooleanMap.html#int2BooleanEntrySet()
* https://fastutil.di.unimi.it/docs/it/unimi/dsi/fastutil/objects/Object2IntMap.html#object2IntEntrySet()

I plan to implement the "suggested fix" component next.

### Update
I've added checks for deprecated methods in `*Iterable`, `*Collection`, `*List`, and `*Set` objects.

### CODE REVIEW

**Comment by jtraglia** [comment]
It's lacking some tests, but seems to work pretty well. Identified a few deprecated `stream()` calls. Ready for an initial code review to make sure I'm on the right path. This check is less annoying than #4.

**Review by ajsutton — APPROVED** [review]
LGTM. I agree this rule is pretty clear cut where as #4 is quite possibly going to be too demanding, at least at this stage.

**Comment by ajsutton** [comment]
Did you want to add some more tests for this? It seems to cover the int cases ok. Might be worth a sanity check of each of the types mostly so we get a failure if the hard coded class names in the check ever need to be updated.

**Comment by jtraglia** [comment]
Yes, I would like to add some tests first. And I would be okay with abandoning #4 if you want. I don't think it really adds that much. Would be annoying for other projects that don't want to use fastutil.

**Comment by jtraglia** [comment]
I'll add tests for other types in a bit.

**Comment by jtraglia** [comment]
Okay. If testing the generic functions for each of the types is sufficient, I believe I'm done with this.

**Pull request merged**
