### PR TITLE
Check for types that can be converted to fastutil

### PR DESCRIPTION
**Pull request by jtraglia**
This check will identify all instantiations of types that could be converted to fastutil types. These are:

* ArrayList
* HashMap
* HashSet
* IdentityHashMap
* LinkedHashMap
* LinkedHashSet
* Stack
* TreeMap
* TreeSet

Currently, this only gives an error. I plan to implement the "suggested fix" component next.

This is classified as a suggestion, not a warning/error. I have not yet tested it against Teku codebase.

### CODE REVIEW

**Comment by jtraglia** [comment]
I should note that only instances that use a primitive type are identified.

**Comment by jtraglia** [comment]
Currently, these suggestions look like:

<details closed>
<summary>List of integers from List.of() method</summary>

```
/tech/pegasys/tools/epchecks/UseFastutilPositiveCases.java:35: Note: [UseFastutil] Use the fastutil equivalent for better performance.
    List<Integer> list_of_ints = List.of(1, 2, 3);
                  ^
  Did you mean 'IntList list_of_ints = IntList.of(1, 2, 3)'?
```
</details>

<details closed>
<summary>List of integers as new array list</summary>

```
/tech/pegasys/tools/epchecks/UseFastutilPositiveCases.java:48: Note: [UseFastutil] Use the fastutil equivalent for better performance.
    List<Byte> bytes = new ArrayList<>();
               ^
  Did you mean 'ByteList bytes = new ByteArrayList()'?
```
</details>

<details closed>
<summary>Integer to string map</summary>

```
/tech/pegasys/tools/epchecks/UseFastutilPositiveCases.java:157: Note: [UseFastutil] Use the fastutil equivalent for better performance.
    Map<Integer, String> int_to_str = new HashMap<>();
                         ^
  Did you mean 'Int2ObjectMap<String> int_to_str = new Int2ObjectOpenHashMap<String>()'?
```
</details>

<details closed>
<summary>Map of maps</summary>

```
/tech/pegasys/tools/epchecks/UseFastutilPositiveCases.java:164: Note: [UseFastutil] Use the fastutil equivalent for better performance.
    Map<Integer, Map<String, String>> int_to_map = new HashMap<>();
                                      ^
  Did you mean 'Int2ObjectMap<Map<String, String>> int_to_map = new Int2ObjectOpenHashMap<Map<String, String>>()'?
```
</details>

**Comment by jtraglia** [comment]
Not even sure this is something we want; it could just be an annoyance. This was really just an excuse to learn how to use errorprone (it's really cool!). There are a few dozen findings in the Teku codebase. I think it works as expected though. Please review.

**Comment by ajsutton** [comment]
Continuing the discussion from #5 here.  I suspect this isn't something we'd enable all the time, but not entirely sure if we should abandon it or not.  I wonder if we can add it but default it to off.  Then if we want to do a pass of reviewing what could be switched over we can enable to for a run and disable again.

**Comment by jtraglia** [comment]
I couldn't figure out a great way to disable the check by default. The only thing I could think of was to use an environment variable. What are your thoughts on this? Enable it by running `USE_FASTUTIL=1 ./gradlew build` on unix systems.

**Comment by ajsutton** [comment]
It's ok we can disable checks fairly easily in the gradle config for projects, I was just hoping there was a way to start with the severity at OFF and then if we want the check we can increase that. It might be worth looking at `WildcardImport` since we seem to be enabling that specifically in teku:
```
      check('WildcardImport', net.ltgt.gradle.errorprone.CheckSeverity.WARN)
```

but not sure if that's at the error prone rule level or the gradle plugin level.

**Comment by jtraglia** [comment]
`WildcardImport` is part of the list of checks that are disabled by default (`DISABLED_CHECKS`).

https://github.com/google/error-prone/blob/54e16466efd935b01c7008d300ab8478c9013d6c/core/src/main/java/com/google/errorprone/scanner/BuiltInCheckerSuppliers.java#L1129

I  do not believe we can modify this list, can we?

**Comment by jtraglia** [comment]
I'm going to add this to my personal tools.

**Pull request closed without merging**
